Repository wecode-bootcamp-korea/fullstack2-1st-dashincode-frontend, pull requests merged in 2021-10, with the labels that each got.

#14 Add: Footer Component 추가
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: 피어 리뷰 요청

#18 Add: navBar Component 추가
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
Labels: Status: 피어 리뷰 요청

#13 [안다빈] Header Component 추가
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Header/logo.png
  src/components/Header/logo_korean.png
Labels: Status: 추가 기능 구현 중

#25 [안다빈] footer 컴포넌트 기능구현
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/footerData.js
Labels: Status: 피어 리뷰 요청

#16 [안다빈] SideBar Component 추가
  package-lock.json
  package.json
  public/data/currentviewed.json
  src/components/SideBar/ScrollTo.js
  src/components/SideBar/ScrollTo.scss
  src/components/SideBar/SideBar.js
  src/components/SideBar/SideBar.scss
  src/components/SideBar/감자.jpeg
  src/pages/Main.js
Labels: status: 기능 구현중

#24 [신정호] 로그인 페이지 레이아웃
  package.json
  src/components/LoginPage/LoginPage.js
  src/components/LoginPage/LoginPage.scss
  src/components/LoginPage/findId.js
  src/components/LoginPage/findPw.js
  src/pages/Login.js
Labels: Status: 피어 리뷰 요청

#35 [안다빈] detail 페이지 description scroll 기능 제외한 나머지 완료
  public/data/detail.json
  public/images/image0.jpg
  public/images/image1.jpg
  public/images/image2.jpg
  public/images/image3.jpg
  public/images/image4.jpg
  src/Routes.js
  src/components/ProductDescription/ProductDescription.js
  src/components/ProductDescription/ProductDescription.scss
  src/components/ProductDescription/detail.jpg
  src/components/ProductDescription/info.jpg
  src/components/ProductInfo/ProductInfo.js
  src/components/ProductInfo/ProductInfo.scss
  src/components/ProductInfo/ico_sns_facebook.gif
  src/components/ProductInfo/ico_sns_kakaostory.gif
  src/components/ProductInfo/ico_sns_twitter.gif
  src/components/ProductNav/ProductNav.js
  src/components/ProductNav/ProductNav.scss
  src/components/ScrollToTop.js
  src/components/SideBar/ScrollTo.js
  src/components/SideBar/ScrollTo.scss
  src/components/SideBar/SideBar.js
  src/components/SideBar/SideBar.scss
  src/pages/Product.js
Labels: Status: 추가 기능 구현 중
